//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "9.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SigTradeEN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SigTradeEN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.SigTradeEN", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save current selection.
        /// </summary>
        internal static string btnSaveSpecies {
            get {
                return ResourceManager.GetString("btnSaveSpecies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select combination.
        /// </summary>
        internal static string btnSelected {
            get {
                return ResourceManager.GetString("btnSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        internal static string hdDetailsAction {
            get {
                return ResourceManager.GetString("hdDetailsAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        internal static string hdDetailsActionOrder {
            get {
                return ResourceManager.GetString("hdDetailsActionOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage.
        /// </summary>
        internal static string hdDetailsParagraph {
            get {
                return ResourceManager.GetString("hdDetailsParagraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm new password.
        /// </summary>
        internal static string lblAccountChangePasswordConfirmPassword {
            get {
                return ResourceManager.GetString("lblAccountChangePasswordConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password.
        /// </summary>
        internal static string lblAccountChangePasswordCurrentPassword {
            get {
                return ResourceManager.GetString("lblAccountChangePasswordCurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your new password details below.
        /// </summary>
        internal static string lblAccountChangePasswordLegend {
            get {
                return ResourceManager.GetString("lblAccountChangePasswordLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        internal static string lblAccountChangePasswordNewPassword {
            get {
                return ResourceManager.GetString("lblAccountChangePasswordNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please use the form below to change your password.
        ///         Please note, new passwords are required to be a minimum of 6 characters long..
        /// </summary>
        internal static string lblAccountChangePasswordNote {
            get {
                return ResourceManager.GetString("lblAccountChangePasswordNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        internal static string lblAccountChangePasswordSubmit {
            get {
                return ResourceManager.GetString("lblAccountChangePasswordSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been changed successfully..
        /// </summary>
        internal static string lblAccountChangePasswordSuccess {
            get {
                return ResourceManager.GetString("lblAccountChangePasswordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        internal static string lblAccountChangePasswordTitle {
            get {
                return ResourceManager.GetString("lblAccountChangePasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password| Please note, passwords must be a minimum of 6 characters..
        /// </summary>
        internal static string lblAccountChangePasswordToolTip {
            get {
                return ResourceManager.GetString("lblAccountChangePasswordToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can edit the account below..
        /// </summary>
        internal static string lblAccountEditNote {
            get {
                return ResourceManager.GetString("lblAccountEditNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Account.
        /// </summary>
        internal static string lblAccountEditTitle {
            get {
                return ResourceManager.GetString("lblAccountEditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address 1.
        /// </summary>
        internal static string lblAccountFormAddress1 {
            get {
                return ResourceManager.GetString("lblAccountFormAddress1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address 2.
        /// </summary>
        internal static string lblAccountFormAddress2 {
            get {
                return ResourceManager.GetString("lblAccountFormAddress2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address 3.
        /// </summary>
        internal static string lblAccountFormAddress3 {
            get {
                return ResourceManager.GetString("lblAccountFormAddress3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        internal static string lblAccountFormConfirmPassword {
            get {
                return ResourceManager.GetString("lblAccountFormConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter contact information.
        /// </summary>
        internal static string lblAccountFormContactInfo {
            get {
                return ResourceManager.GetString("lblAccountFormContactInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string lblAccountFormCountry {
            get {
                return ResourceManager.GetString("lblAccountFormCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string lblAccountFormEmail {
            get {
                return ResourceManager.GetString("lblAccountFormEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string lblAccountFormFirstName {
            get {
                return ResourceManager.GetString("lblAccountFormFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string lblAccountFormLastName {
            get {
                return ResourceManager.GetString("lblAccountFormLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Information.
        /// </summary>
        internal static string lblAccountFormLegend {
            get {
                return ResourceManager.GetString("lblAccountFormLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to optional.
        /// </summary>
        internal static string lblAccountFormOptional {
            get {
                return ResourceManager.GetString("lblAccountFormOptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string lblAccountFormPassword {
            get {
                return ResourceManager.GetString("lblAccountFormPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postcode.
        /// </summary>
        internal static string lblAccountFormPostcode {
            get {
                return ResourceManager.GetString("lblAccountFormPostcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string lblAccountFormRegister {
            get {
                return ResourceManager.GetString("lblAccountFormRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State or County.
        /// </summary>
        internal static string lblAccountFormStateCounty {
            get {
                return ResourceManager.GetString("lblAccountFormStateCounty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone.
        /// </summary>
        internal static string lblAccountFormTelephone {
            get {
                return ResourceManager.GetString("lblAccountFormTelephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Town or City.
        /// </summary>
        internal static string lblAccountFormTownCity {
            get {
                return ResourceManager.GetString("lblAccountFormTownCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string lblAccountFormUserName {
            get {
                return ResourceManager.GetString("lblAccountFormUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string lblAccountListLogOnPassword {
            get {
                return ResourceManager.GetString("lblAccountListLogOnPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me?.
        /// </summary>
        internal static string lblAccountListLogOnRemember {
            get {
                return ResourceManager.GetString("lblAccountListLogOnRemember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log On.
        /// </summary>
        internal static string lblAccountListLogOnSubmit {
            get {
                return ResourceManager.GetString("lblAccountListLogOnSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string lblAccountListLogOnUsername {
            get {
                return ResourceManager.GetString("lblAccountListLogOnUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string lblAccountListTableEmail {
            get {
                return ResourceManager.GetString("lblAccountListTableEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string lblAccountListTableUsername {
            get {
                return ResourceManager.GetString("lblAccountListTableUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Users.
        /// </summary>
        internal static string lblAccountListTitle {
            get {
                return ResourceManager.GetString("lblAccountListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Users.
        /// </summary>
        internal static string lblAccountListUsers {
            get {
                return ResourceManager.GetString("lblAccountListUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Information.
        /// </summary>
        internal static string lblAccountLogOnLegend {
            get {
                return ResourceManager.GetString("lblAccountLogOnLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your username and password..
        /// </summary>
        internal static string lblAccountLogOnNote {
            get {
                return ResourceManager.GetString("lblAccountLogOnNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log On.
        /// </summary>
        internal static string lblAccountLogOnTitle {
            get {
                return ResourceManager.GetString("lblAccountLogOnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can create a new account below..
        /// </summary>
        internal static string lblAccountNewCreateText {
            get {
                return ResourceManager.GetString("lblAccountNewCreateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a New Account.
        /// </summary>
        internal static string lblAccountNewTitle {
            get {
                return ResourceManager.GetString("lblAccountNewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type your e-mail address into the box and a new password will be sent to you..
        /// </summary>
        internal static string lblAccountPasswordReminderInstructions {
            get {
                return ResourceManager.GetString("lblAccountPasswordReminderInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail for.
        /// </summary>
        internal static string lblAccountShowDetail {
            get {
                return ResourceManager.GetString("lblAccountShowDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Roles.
        /// </summary>
        internal static string lblAccountShowLegend {
            get {
                return ResourceManager.GetString("lblAccountShowLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show User.
        /// </summary>
        internal static string lblAccountShowTitle {
            get {
                return ResourceManager.GetString("lblAccountShowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the security level of to users| 
        ///    &lt;p&gt;These settings affect both the ability to update data, and view data.&lt;/p&gt;
        ///    &lt;p&gt;Please note the following hierachy:&lt;/p&gt;
        ///    &lt;h6&gt;Data writing&lt;/h6&gt;
        ///    &lt;ul&gt;
        ///        &lt;li&gt;Administrator&lt;/li&gt;
        ///        &lt;li&gt;Data Manager&lt;/li&gt;
        ///        &lt;li&gt;Data Contributor&lt;/li&gt;
        ///    &lt;/ul&gt;
        ///
        ///    &lt;h6&gt;Data reading&lt;/h6&gt;
        ///    &lt;ul&gt;
        ///        &lt;li&gt;Full Viewer&lt;/li&gt;
        ///        &lt;li&gt;Intermediate Viewer&lt;/li&gt;
        ///        &lt;li&gt;Public Viewer&lt;/li&gt;
        ///    &lt;/ul&gt;
        ///  
        ///    &lt;div class=&quot;notice&quot;&gt;Selecting a highe [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lblAccountShowToolTip {
            get {
                return ResourceManager.GetString("lblAccountShowToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Actors.
        /// </summary>
        internal static string lblAddActors {
            get {
                return ResourceManager.GetString("lblAddActors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert comment:.
        /// </summary>
        internal static string lblAddComment {
            get {
                return ResourceManager.GetString("lblAddComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment Access:.
        /// </summary>
        internal static string lblAddCommentType {
            get {
                return ResourceManager.GetString("lblAddCommentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a committee:.
        /// </summary>
        internal static string lblAddCommittee {
            get {
                return ResourceManager.GetString("lblAddCommittee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select country.
        /// </summary>
        internal static string lblAddCountry {
            get {
                return ResourceManager.GetString("lblAddCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add the Country.
        /// </summary>
        internal static string lblAddCountryTitle {
            get {
                return ResourceManager.GetString("lblAddCountryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date .
        /// </summary>
        internal static string lblAddDateStarted {
            get {
                return ResourceManager.GetString("lblAddDateStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select deadline.
        /// </summary>
        internal static string lblAddDeadline {
            get {
                return ResourceManager.GetString("lblAddDeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string lblAddDecision {
            get {
                return ResourceManager.GetString("lblAddDecision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Link:.
        /// </summary>
        internal static string lblAddDocument {
            get {
                return ResourceManager.GetString("lblAddDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Access.
        /// </summary>
        internal static string lblAddDocumentAccess {
            get {
                return ResourceManager.GetString("lblAddDocumentAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OR Add Hyperlink.
        /// </summary>
        internal static string lblAddHyperlink {
            get {
                return ResourceManager.GetString("lblAddHyperlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suspension Lifted Date.
        /// </summary>
        internal static string lblAddLiftedDate {
            get {
                return ResourceManager.GetString("lblAddLiftedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a meeting:.
        /// </summary>
        internal static string lblAddMeeting {
            get {
                return ResourceManager.GetString("lblAddMeeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the Phase.
        /// </summary>
        internal static string lblAddPhase {
            get {
                return ResourceManager.GetString("lblAddPhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Phase.
        /// </summary>
        internal static string lblAddPhaseTitle {
            get {
                return ResourceManager.GetString("lblAddPhaseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommendation Date.
        /// </summary>
        internal static string lblAddRecDate {
            get {
                return ResourceManager.GetString("lblAddRecDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deadline Date.
        /// </summary>
        internal static string lblAddRecDeadline {
            get {
                return ResourceManager.GetString("lblAddRecDeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommendation.
        /// </summary>
        internal static string lblAddRecommendation {
            get {
                return ResourceManager.GetString("lblAddRecommendation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animal.
        /// </summary>
        internal static string lblAddReviewAnimals {
            get {
                return ResourceManager.GetString("lblAddReviewAnimals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2) Select Committee.
        /// </summary>
        internal static string lblAddReviewCommittee {
            get {
                return ResourceManager.GetString("lblAddReviewCommittee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5) Select Country.
        /// </summary>
        internal static string lblAddReviewCountry {
            get {
                return ResourceManager.GetString("lblAddReviewCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4) Select Review Date.
        /// </summary>
        internal static string lblAddReviewDate {
            get {
                return ResourceManager.GetString("lblAddReviewDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add your review data below.
        /// </summary>
        internal static string lblAddReviewFormLegend {
            get {
                return ResourceManager.GetString("lblAddReviewFormLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genus:.
        /// </summary>
        internal static string lblAddReviewGenus {
            get {
                return ResourceManager.GetString("lblAddReviewGenus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3) Select Kingdom.
        /// </summary>
        internal static string lblAddReviewKingdom {
            get {
                return ResourceManager.GetString("lblAddReviewKingdom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1) Select Phase.
        /// </summary>
        internal static string lblAddReviewPhase {
            get {
                return ResourceManager.GetString("lblAddReviewPhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plant.
        /// </summary>
        internal static string lblAddReviewPlants {
            get {
                return ResourceManager.GetString("lblAddReviewPlants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Species:.
        /// </summary>
        internal static string lblAddReviewSpecies {
            get {
                return ResourceManager.GetString("lblAddReviewSpecies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4) Select Genus/Species.
        /// </summary>
        internal static string lblAddReviewSpeciesFS {
            get {
                return ResourceManager.GetString("lblAddReviewSpeciesFS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubSpecies:.
        /// </summary>
        internal static string lblAddReviewSubSpecies {
            get {
                return ResourceManager.GetString("lblAddReviewSubSpecies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new Review.
        /// </summary>
        internal static string lblAddReviewTitle {
            get {
                return ResourceManager.GetString("lblAddReviewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad-Hoc.
        /// </summary>
        internal static string lblAddReviewTypeAdhoc {
            get {
                return ResourceManager.GetString("lblAddReviewTypeAdhoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string lblAddReviewTypeNormal {
            get {
                return ResourceManager.GetString("lblAddReviewTypeNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add the Species.
        /// </summary>
        internal static string lblAddSpeciesTitle {
            get {
                return ResourceManager.GetString("lblAddSpeciesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decision/Suspension Date.
        /// </summary>
        internal static string lblAddSuspensionDate {
            get {
                return ResourceManager.GetString("lblAddSuspensionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade Terms.
        /// </summary>
        internal static string lblAddTradeTerms {
            get {
                return ResourceManager.GetString("lblAddTradeTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach Document.
        /// </summary>
        internal static string lblAttachDocument {
            get {
                return ResourceManager.GetString("lblAttachDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Class.
        /// </summary>
        internal static string lblClass {
            get {
                return ResourceManager.GetString("lblClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Committee Description.
        /// </summary>
        internal static string lblCommitteeDescription {
            get {
                return ResourceManager.GetString("lblCommitteeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Committee.
        /// </summary>
        internal static string lblCommitteeEditTitle {
            get {
                return ResourceManager.GetString("lblCommitteeEditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Committee Details.
        /// </summary>
        internal static string lblCommitteeLegend {
            get {
                return ResourceManager.GetString("lblCommitteeLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string lblCommitteeListDescription {
            get {
                return ResourceManager.GetString("lblCommitteeListDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Committees.
        /// </summary>
        internal static string lblCommitteeListTitle {
            get {
                return ResourceManager.GetString("lblCommitteeListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can create a new committee below..
        /// </summary>
        internal static string lblCommitteeNotes {
            get {
                return ResourceManager.GetString("lblCommitteeNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string lblCommitteeSubmit {
            get {
                return ResourceManager.GetString("lblCommitteeSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Committee.
        /// </summary>
        internal static string lblCommitteeTitle {
            get {
                return ResourceManager.GetString("lblCommitteeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lvl Concern.
        /// </summary>
        internal static string lblConcernList {
            get {
                return ResourceManager.GetString("lblConcernList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string lblCountryList {
            get {
                return ResourceManager.GetString("lblCountryList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Added.
        /// </summary>
        internal static string lblDateList {
            get {
                return ResourceManager.GetString("lblDateList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deadline.
        /// </summary>
        internal static string lblDeadlineList {
            get {
                return ResourceManager.GetString("lblDeadlineList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decision Type.
        /// </summary>
        internal static string lblDecisionType {
            get {
                return ResourceManager.GetString("lblDecisionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The stages are defined in paragraphs (a) to (v) of Conf. 12.8 (Rev. CoP13).
        /// </summary>
        internal static string lblDetailsText {
            get {
                return ResourceManager.GetString("lblDetailsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Legend.
        /// </summary>
        internal static string lblDocLegend {
            get {
                return ResourceManager.GetString("lblDocLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Comment.
        /// </summary>
        internal static string lblEditCommentTitle {
            get {
                return ResourceManager.GetString("lblEditCommentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please make your changes and save.
        /// </summary>
        internal static string lblEditReviewFormLegend {
            get {
                return ResourceManager.GetString("lblEditReviewFormLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Review.
        /// </summary>
        internal static string lblEditReviewTitle {
            get {
                return ResourceManager.GetString("lblEditReviewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Family.
        /// </summary>
        internal static string lblFamily {
            get {
                return ResourceManager.GetString("lblFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This database was created by and is maintained by &lt;a href=&quot;http://www.unep-wcmc.org&quot;&gt;UNEP-WCMC&lt;/a&gt; on behalf of the CITES Secretariat..
        /// </summary>
        internal static string lblFooter {
            get {
                return ResourceManager.GetString("lblFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgotten Password.
        /// </summary>
        internal static string lblForgottenPassword {
            get {
                return ResourceManager.GetString("lblForgottenPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgotten Password?.
        /// </summary>
        internal static string lblForgottenPasswordQuestion {
            get {
                return ResourceManager.GetString("lblForgottenPasswordQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the Species (e.g genus + species).
        /// </summary>
        internal static string lblFreeSearch {
            get {
                return ResourceManager.GetString("lblFreeSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Genus.
        /// </summary>
        internal static string lblGenus {
            get {
                return ResourceManager.GetString("lblGenus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kingdom .
        /// </summary>
        internal static string lblKingdomList {
            get {
                return ResourceManager.GetString("lblKingdomList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a kingdom:.
        /// </summary>
        internal static string lblKingdom_Text {
            get {
                return ResourceManager.GetString("lblKingdom.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting at which suspension was lifted.
        /// </summary>
        internal static string lblLiftedCommitee {
            get {
                return ResourceManager.GetString("lblLiftedCommitee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting details.
        /// </summary>
        internal static string lblMeetingEditLegend {
            get {
                return ResourceManager.GetString("lblMeetingEditLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Meeting.
        /// </summary>
        internal static string lblMeetingEditTitle {
            get {
                return ResourceManager.GetString("lblMeetingEditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter meeting details.
        /// </summary>
        internal static string lblMeetingLegend {
            get {
                return ResourceManager.GetString("lblMeetingLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting Date.
        /// </summary>
        internal static string lblMeetingLibDate {
            get {
                return ResourceManager.GetString("lblMeetingLibDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting Description.
        /// </summary>
        internal static string lblMeetingLibDescription {
            get {
                return ResourceManager.GetString("lblMeetingLibDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting Number.
        /// </summary>
        internal static string lblMeetingLibNumber {
            get {
                return ResourceManager.GetString("lblMeetingLibNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Meeting.
        /// </summary>
        internal static string lblMeetingLibSubmit {
            get {
                return ResourceManager.GetString("lblMeetingLibSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Meeting.
        /// </summary>
        internal static string lblMeetingLibUpdate {
            get {
                return ResourceManager.GetString("lblMeetingLibUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string lblMeetingListCode {
            get {
                return ResourceManager.GetString("lblMeetingListCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comittee.
        /// </summary>
        internal static string lblMeetingListComittee {
            get {
                return ResourceManager.GetString("lblMeetingListComittee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string lblMeetingListDate {
            get {
                return ResourceManager.GetString("lblMeetingListDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Meetings.
        /// </summary>
        internal static string lblMeetingListTitle {
            get {
                return ResourceManager.GetString("lblMeetingListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Meeting.
        /// </summary>
        internal static string lblMeetingTitle {
            get {
                return ResourceManager.GetString("lblMeetingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Template.
        /// </summary>
        internal static string lblMessageTemplateSubmit {
            get {
                return ResourceManager.GetString("lblMessageTemplateSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Search Results Found!.
        /// </summary>
        internal static string lblNoSearchResults {
            get {
                return ResourceManager.GetString("lblNoSearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an Order.
        /// </summary>
        internal static string lblOrder {
            get {
                return ResourceManager.GetString("lblOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments:.
        /// </summary>
        internal static string lblPAComments {
            get {
                return ResourceManager.GetString("lblPAComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Committee.
        /// </summary>
        internal static string lblPACommittee {
            get {
                return ResourceManager.GetString("lblPACommittee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        internal static string lblPACompleted {
            get {
                return ResourceManager.GetString("lblPACompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Concern Level:.
        /// </summary>
        internal static string lblPAConcern {
            get {
                return ResourceManager.GetString("lblPAConcern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Concern:.
        /// </summary>
        internal static string lblPACurrentConcern {
            get {
                return ResourceManager.GetString("lblPACurrentConcern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed Date.
        /// </summary>
        internal static string lblPADateCompleted {
            get {
                return ResourceManager.GetString("lblPADateCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Started.
        /// </summary>
        internal static string lblPADateStarted {
            get {
                return ResourceManager.GetString("lblPADateStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deadline Date.
        /// </summary>
        internal static string lblPADeadline {
            get {
                return ResourceManager.GetString("lblPADeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage.
        /// </summary>
        internal static string lblPADetails {
            get {
                return ResourceManager.GetString("lblPADetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents:.
        /// </summary>
        internal static string lblPADocuments {
            get {
                return ResourceManager.GetString("lblPADocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting.
        /// </summary>
        internal static string lblPAMeeting {
            get {
                return ResourceManager.GetString("lblPAMeeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage.
        /// </summary>
        internal static string lblParagraphList {
            get {
                return ResourceManager.GetString("lblParagraphList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Actors:.
        /// </summary>
        internal static string lblPASelectActors {
            get {
                return ResourceManager.GetString("lblPASelectActors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Reset.
        /// </summary>
        internal static string lblPasswordReset {
            get {
                return ResourceManager.GetString("lblPasswordReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new password has been e-mailed to the address which you provided..
        /// </summary>
        internal static string lblPassWordResetSuccessful {
            get {
                return ResourceManager.GetString("lblPassWordResetSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Phase.
        /// </summary>
        internal static string lblPhaseCreateTitle {
            get {
                return ResourceManager.GetString("lblPhaseCreateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Phase.
        /// </summary>
        internal static string lblPhaseEditTitle {
            get {
                return ResourceManager.GetString("lblPhaseEditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phase Description.
        /// </summary>
        internal static string lblPhaseFormDescription {
            get {
                return ResourceManager.GetString("lblPhaseFormDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phase Details.
        /// </summary>
        internal static string lblPhaseFormLegend {
            get {
                return ResourceManager.GetString("lblPhaseFormLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        internal static string lblPhaseFormStartDate {
            get {
                return ResourceManager.GetString("lblPhaseFormStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string lblPhaseFormSubmit {
            get {
                return ResourceManager.GetString("lblPhaseFormSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phase .
        /// </summary>
        internal static string lblPhaseList {
            get {
                return ResourceManager.GetString("lblPhaseList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phase Description.
        /// </summary>
        internal static string lblPhaseListDescription {
            get {
                return ResourceManager.GetString("lblPhaseListDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        internal static string lblPhaseListStartDate {
            get {
                return ResourceManager.GetString("lblPhaseListStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Phases.
        /// </summary>
        internal static string lblPhaseListTitle {
            get {
                return ResourceManager.GetString("lblPhaseListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can create a new phase below..
        /// </summary>
        internal static string lblPhaseNote {
            get {
                return ResourceManager.GetString("lblPhaseNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Phase.
        /// </summary>
        internal static string lblPhaseTitle {
            get {
                return ResourceManager.GetString("lblPhaseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Phylum.
        /// </summary>
        internal static string lblPhylum {
            get {
                return ResourceManager.GetString("lblPhylum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to indicates a required field..
        /// </summary>
        internal static string lblRedStar {
            get {
                return ResourceManager.GetString("lblRedStar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a Review.
        /// </summary>
        internal static string lblReviewIndexTitle {
            get {
                return ResourceManager.GetString("lblReviewIndexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of reviews currently active.
        /// </summary>
        internal static string lblReviewsList {
            get {
                return ResourceManager.GetString("lblReviewsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current reviews in progress. Click a review to see its current status..
        /// </summary>
        internal static string lblReviewsListIntro {
            get {
                return ResourceManager.GetString("lblReviewsListIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Type.
        /// </summary>
        internal static string lblReviewTypeList {
            get {
                return ResourceManager.GetString("lblReviewTypeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Rights.
        /// </summary>
        internal static string lblRoleAccess {
            get {
                return ResourceManager.GetString("lblRoleAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Name.
        /// </summary>
        internal static string lblRoleListName {
            get {
                return ResourceManager.GetString("lblRoleListName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listing Roles.
        /// </summary>
        internal static string lblRoleListTitle {
            get {
                return ResourceManager.GetString("lblRoleListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add another user to this role.
        /// </summary>
        internal static string lblRoleShowLegend {
            get {
                return ResourceManager.GetString("lblRoleShowLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Role.
        /// </summary>
        internal static string lblRoleShowTitle {
            get {
                return ResourceManager.GetString("lblRoleShowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string lblRoleTableEmail {
            get {
                return ResourceManager.GetString("lblRoleTableEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove user from role.
        /// </summary>
        internal static string lblRoleTableRemoveUser {
            get {
                return ResourceManager.GetString("lblRoleTableRemoveUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string lblRoleTableUsername {
            get {
                return ResourceManager.GetString("lblRoleTableUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or search by country:.
        /// </summary>
        internal static string lblSearchCountry {
            get {
                return ResourceManager.GetString("lblSearchCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OR.
        /// </summary>
        internal static string lblSearchOr {
            get {
                return ResourceManager.GetString("lblSearchOr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for Review.
        /// </summary>
        internal static string lblSearchPageTitle {
            get {
                return ResourceManager.GetString("lblSearchPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The CITES Review of Significant Trade procedure (defined in &lt;a href=&quot;http://www.cites.org/eng/res/12/12-08R13.shtml&quot;&gt;Conf. 12.8 (Rev. CoP13)&lt;/a&gt;)
        ///was designed to identify species that may be subject to unsustainable levels of international trade, and to identify problems and solutions concerning effective implementation of the Convention.
        /// 
        ///This system tracks the progress of species for the range States that have been selected for review, through the 22 stages of the Significant Trade Review Procedure. S [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lblSearchText {
            get {
                return ResourceManager.GetString("lblSearchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Species/Country.
        /// </summary>
        internal static string lblSelectedSpecies {
            get {
                return ResourceManager.GetString("lblSelectedSpecies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Species.
        /// </summary>
        internal static string lblSpecies {
            get {
                return ResourceManager.GetString("lblSpecies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Status .
        /// </summary>
        internal static string lblStatusList {
            get {
                return ResourceManager.GetString("lblStatusList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting at which suspension was established.
        /// </summary>
        internal static string lblSuspensionCommittee {
            get {
                return ResourceManager.GetString("lblSuspensionCommittee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxon Name .
        /// </summary>
        internal static string lblTaxonNameList {
            get {
                return ResourceManager.GetString("lblTaxonNameList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxon Rank .
        /// </summary>
        internal static string lblTaxonRankList {
            get {
                return ResourceManager.GetString("lblTaxonRankList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have access rights.
        /// </summary>
        internal static string lblUserDetailsAccessRights {
            get {
                return ResourceManager.GetString("lblUserDetailsAccessRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string lblUserDetailsWelcome {
            get {
                return ResourceManager.GetString("lblUserDetailsWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save + Add Another one.
        /// </summary>
        internal static string textSaveAdd {
            get {
                return ResourceManager.GetString("textSaveAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and Return to List.
        /// </summary>
        internal static string textSaveList {
            get {
                return ResourceManager.GetString("textSaveList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage Details Add.
        /// </summary>
        internal static string titleParagraphDetailsAdd {
            get {
                return ResourceManager.GetString("titleParagraphDetailsAdd", resourceCulture);
            }
        }
    }
}
