//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "9.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SignificantTrade {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SignificantTrade() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.SignificantTrade", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Class.
        /// </summary>
        internal static string lblClass {
            get {
                return ResourceManager.GetString("lblClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Family.
        /// </summary>
        internal static string lblFamily {
            get {
                return ResourceManager.GetString("lblFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Genus.
        /// </summary>
        internal static string lblGenus {
            get {
                return ResourceManager.GetString("lblGenus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a kingdom:.
        /// </summary>
        internal static string lblKingdom_Text {
            get {
                return ResourceManager.GetString("lblKingdom.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an Order.
        /// </summary>
        internal static string lblOrder {
            get {
                return ResourceManager.GetString("lblOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Phylum.
        /// </summary>
        internal static string lblPhylum {
            get {
                return ResourceManager.GetString("lblPhylum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a Review.
        /// </summary>
        internal static string lblReviewIndexTitle {
            get {
                return ResourceManager.GetString("lblReviewIndexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Species.
        /// </summary>
        internal static string lblSpecies {
            get {
                return ResourceManager.GetString("lblSpecies", resourceCulture);
            }
        }
    }
}
