//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "9.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Tooltips {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Tooltips() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Tooltips", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access rights|Full control of data and user rights.
        /// </summary>
        internal static string AccessRightsAdmin {
            get {
                return ResourceManager.GetString("AccessRightsAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access rights|Able to provide responses to the Secretariat.
        /// </summary>
        internal static string AccessRightsDataContributor {
            get {
                return ResourceManager.GetString("AccessRightsDataContributor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access rights|Data rights for approved stages.
        /// </summary>
        internal static string AccessRightsDataManager {
            get {
                return ResourceManager.GetString("AccessRightsDataManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access rights|Able to view all information.
        /// </summary>
        internal static string AccessRightsFullViewer {
            get {
                return ResourceManager.GetString("AccessRightsFullViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access rights|Able to view certain information.
        /// </summary>
        internal static string AccessRightsIntermediateViewer {
            get {
                return ResourceManager.GetString("AccessRightsIntermediateViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access rights|Able to view certain information.
        /// </summary>
        internal static string AccessRightsPublicViewer {
            get {
                return ResourceManager.GetString("AccessRightsPublicViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to |Access to certain areas of the website are restricted to administrators and data managers. .
        /// </summary>
        internal static string Account_LogOn {
            get {
                return ResourceManager.GetString("Account_LogOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Phase| Select the new Phase. New Phases can be added by Administrators using the Site Admin &gt; Phases &gt; New Phase.
        /// </summary>
        internal static string AddReview_AddReview_1 {
            get {
                return ResourceManager.GetString("AddReview_AddReview_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Kingdom|Select Kingdom Plants or Kingdom Animals.
        /// </summary>
        internal static string AddReview_AddReview_2 {
            get {
                return ResourceManager.GetString("AddReview_AddReview_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Genus/Species|Select &lt;i&gt;genus.&lt;/i&gt; Once the genus is selected, species of that genus will be populated in the species box for selection..
        /// </summary>
        internal static string AddReview_AddReview_3 {
            get {
                return ResourceManager.GetString("AddReview_AddReview_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Country| Only known range States of the species selected can be added. If a country is selected for review and it does not occur in the list, contact the administrator..
        /// </summary>
        internal static string AddReview_AddReview_4 {
            get {
                return ResourceManager.GetString("AddReview_AddReview_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level of Concern|The &lt;i&gt;&quot;level of concern&quot; &lt;/i&gt;category is determined by the Animals or Plants Committee following a review of the species biology, management and international trade levels, by the Secretariat or consultants and considering responses by the range States. &lt;br&gt;&lt;br&gt;There are three categories of concern: &lt;br&gt;&lt;b&gt;Species of urgent concern &lt;/b&gt; includes species for which the available information indicates that the provisions of Article IV, paragraph 2(a), 3 or 6(a) are not being implemented &lt;br&gt;  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AddReview_List_1 {
            get {
                return ResourceManager.GetString("AddReview_List_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phase|The selection process for adding new species for review takes place periodically in &lt;i&gt;&quot;Phases&quot; &lt;/i&gt;. &lt;br&gt;The first Phase was established in 1986. A new Phase now follows every meeting of the Conference of the Parties.  .
        /// </summary>
        internal static string AddReview_List_2 {
            get {
                return ResourceManager.GetString("AddReview_List_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage|The current stage of the 22 stage process (a-v) of the Review of Significant Trade as defined in &lt;b&gt;Conf. Res. 12.8 (Rev CoP13).&lt;/b&gt;.
        /// </summary>
        internal static string AddReview_List_3 {
            get {
                return ResourceManager.GetString("AddReview_List_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deadline|Deadlines for each stage may be determined by &lt;b&gt;Conf. Res. 12.8 (Rev. CoP13), &lt;/b&gt;by the meeting dates of the Animals and Plants Committee or they can be set by the Animals or Plants Committee, where for example, a range State is required to respond to specific recommendations of the AC/PC. .
        /// </summary>
        internal static string AddReview_List_4 {
            get {
                return ResourceManager.GetString("AddReview_List_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting Code | The abbreviated meeting code, e.g. Animals Committee 24 is represented as &lt;b&gt;AC24.&lt;/b&gt;.
        /// </summary>
        internal static string Meetings_Create_1 {
            get {
                return ResourceManager.GetString("Meetings_Create_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting Date | The start date of the meeting..
        /// </summary>
        internal static string Meetings_Create_2 {
            get {
                return ResourceManager.GetString("Meetings_Create_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date | Add the start date of the meeting or date of intersessional activity..
        /// </summary>
        internal static string ParagraphDetails_Add_Review_1 {
            get {
                return ResourceManager.GetString("ParagraphDetails_Add_Review_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actors | Select the actor relevant to the stage (a-v).
        /// </summary>
        internal static string ParagraphDetails_Add_Review_2 {
            get {
                return ResourceManager.GetString("ParagraphDetails_Add_Review_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add comments | Add any relevant comments relating to the review..
        /// </summary>
        internal static string ParagraphDetails_Add_Review_3 {
            get {
                return ResourceManager.GetString("ParagraphDetails_Add_Review_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document name | Name files using the following protocol: Genus_species_two letter ISOcountry code.doc. For example:  Prunus_africana_KE.  Use underscores rather than spaces,  and avoid using characters that are not letters of the alphabet..
        /// </summary>
        internal static string ParagraphDetails_Add_Review_4 {
            get {
                return ResourceManager.GetString("ParagraphDetails_Add_Review_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Hyperlinks | If the location of a document on a website changes, this link will be broken.  &lt;br&gt;&lt;br&gt;It is preferable to upload documents if possible..
        /// </summary>
        internal static string ParagraphDetails_Add_Review_5 {
            get {
                return ResourceManager.GetString("ParagraphDetails_Add_Review_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action|The action required within each stage of the Review of Significant Trade..
        /// </summary>
        internal static string ProcessReview_Details_1 {
            get {
                return ResourceManager.GetString("ProcessReview_Details_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage Details|&lt;b&gt;&lt;i&gt;Compilation of information and preliminary categorization&lt;/b&gt;&lt;/i&gt;&lt;br&gt;&lt;br&gt;&lt;b&gt;g)&lt;/b&gt;in the event that the species is not eliminated from the review in accordance with paragraph f), the Secretariat shall proceed with the compilation of information regarding the species &lt;br&gt;&lt;br&gt;&lt;b&gt;h)&lt;/b&gt; when necessary, consultants shall be engaged by the Secretariat to compile information about the biology and management of and trade in the species and shall contact the range States or relevant experts to o [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ProcessReview_Details_10GH {
            get {
                return ResourceManager.GetString("ProcessReview_Details_10GH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage Details|&lt;b&gt;&lt;i&gt;Compilation of information and preliminary categorization&lt;/b&gt;&lt;/i&gt;&lt;br&gt;&lt;br&gt;&lt;b&gt;i)&lt;/b&gt; the Secretariat or consultants, as appropriate, shall summarize their conclusions about the effects of international trade on the selected species, the basis on which such conclusions are made and problems concerning the implementation of Article IV, and shall provisionally divide the selected species into three categories: &lt;br&gt;&lt;br&gt;&lt;b&gt;i)&lt;i&gt; ‘species of urgent concern’ &lt;/b&gt;&lt;/i&gt;shall include species for whic [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ProcessReview_Details_11I {
            get {
                return ResourceManager.GetString("ProcessReview_Details_11I", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage Details|&lt;b&gt;&lt;i&gt; Compilation of information and preliminary categorization&lt;/b&gt;&lt;/i&gt;&lt;br&gt;&lt;br&gt;&lt;b&gt;j)&lt;/b&gt; before the report of the Secretariat, or consultant, is considered by the Animals or Plants Committee, the Secretariat shall transmit it to the relevant range States, seeking comments and, where appropriate, additional information. Range States shall be given 60 days to respond.
        /// </summary>
        internal static string ProcessReview_Details_12J {
            get {
                return ResourceManager.GetString("ProcessReview_Details_12J", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage Details|&lt;b&gt;&lt;i&gt; Review of information and confirming of categorization by the Animals or Plants Committee&lt;/b&gt;&lt;/i&gt;&lt;br&gt;&lt;br &gt;&lt;b&gt;k)&lt;/b&gt; the Animals or Plants Committee shall review the report of the Secretariat or the consultants and the responses received from the States concerned and, if appropriate, revise the preliminary categorization proposed.
        /// </summary>
        internal static string ProcessReview_Details_13K {
            get {
                return ResourceManager.GetString("ProcessReview_Details_13K", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage Details|&lt;b&gt;&lt;i&gt; Review of information and confirming of categorization by the Animals or Plants Committee&lt;/b&gt;&lt;/i&gt;&lt;br&gt;&lt;br &gt;&lt;b&gt;l)&lt;/b&gt; species of least concern shall be eliminated from the review. Problems identified in the course of the review that are not related to the implementation of Article IV, paragraph 2 (a), 3 or 6 (a), shall be addressed by the Secretariat in accordance with other provisions of the Convention and relevant Resolutions.
        /// </summary>
        internal static string ProcessReview_Details_14L {
            get {
                return ResourceManager.GetString("ProcessReview_Details_14L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage Details|&lt;b&gt;&lt;i&gt; Formulation of recommendations and their transmission to the range States&lt;/b&gt;&lt;/i&gt;&lt;br&gt;&lt;br &gt;&lt;b&gt;m)&lt;/b&gt; the Animals or Plants Committee shall, in consultation with the Secretariat, formulate recommendations for the remaining species. These recommendations shall be directed to the range States concerned. &lt;br&gt;&lt;br&gt;&lt;b&gt;n) &lt;/b&gt;for species of urgent concern, these recommendations should propose specific actions to address problems related to the implementation of Article IV, paragraph 2 (a), 3 or  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ProcessReview_Details_15MN {
            get {
                return ResourceManager.GetString("ProcessReview_Details_15MN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage Details|&lt;b&gt;&lt;i&gt; Formulation of recommendations and their transmission to the range States&lt;/b&gt;&lt;/i&gt;&lt;br&gt;&lt;br &gt;&lt;b&gt;p)&lt;/b&gt; these recommendations shall be transmitted to the range States concerned by the Secretariat.
        /// </summary>
        internal static string ProcessReview_Details_16P {
            get {
                return ResourceManager.GetString("ProcessReview_Details_16P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage Details|&lt;b&gt;&lt;i&gt; Measures to be taken regarding the implementation of recommendations&lt;/b&gt;&lt;/i&gt;&lt;br&gt;&lt;br &gt;&lt;b&gt;q)&lt;/b&gt; the Secretariat shall, in consultation with the Chairman of the Animals or Plants Committee, determine whether the recommendations referred to above have been implemented and report to the Standing Committee accordingly.
        /// </summary>
        internal static string ProcessReview_Details_17Q {
            get {
                return ResourceManager.GetString("ProcessReview_Details_17Q", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage Details|&lt;b&gt;&lt;i&gt; Measures to be taken regarding the implementation of recommendations&lt;/b&gt;&lt;/i&gt;&lt;br&gt;&lt;br &gt;&lt;b&gt;q)&lt;/b&gt; the Secretariat shall, in consultation with the Chairman of the Animals or Plants Committee, determine whether the recommendations referred to above have been implemented and report to the Standing Committee accordingly.
        /// </summary>
        internal static string ProcessReview_Details_18Q {
            get {
                return ResourceManager.GetString("ProcessReview_Details_18Q", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage Details|&lt;b&gt;&lt;i&gt; Measures to be taken regarding the implementation of recommendations&lt;/b&gt;&lt;/i&gt;&lt;br&gt;&lt;br &gt;&lt;b&gt;r)&lt;/b&gt; the recommendations have been met, the Secretariat shall, following consultation with the Chairman of the Standing Committee, notify the Parties that the species was removed from the process.
        /// </summary>
        internal static string ProcessReview_Details_19R {
            get {
                return ResourceManager.GetString("ProcessReview_Details_19R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage|The current stage of the 22 stage process (a-v) of the Review of Significant Trade as defined in &lt;b&gt;Conf. Res. 12.8 (Rev CoP13) &lt;/b&gt;is highlighted..
        /// </summary>
        internal static string ProcessReview_Details_2 {
            get {
                return ResourceManager.GetString("ProcessReview_Details_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage Details|&lt;b&gt;&lt;i&gt; Measures to be taken regarding the implementation of recommendations&lt;/b&gt;&lt;/i&gt;&lt;br&gt;&lt;br &gt;&lt;b&gt;r)&lt;/b&gt; the recommendations have been met, the Secretariat shall, following consultation with the Chairman of the Standing Committee, notify the Parties that the species was removed from the process.
        /// </summary>
        internal static string ProcessReview_Details_20R {
            get {
                return ResourceManager.GetString("ProcessReview_Details_20R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage Details|&lt;b&gt;&lt;i&gt; Measures to be taken regarding the implementation of recommendations&lt;/b&gt;&lt;/i&gt;&lt;br&gt;&lt;br &gt;&lt;b&gt;s)&lt;/b&gt;when the Secretariat, having consulted with the Chairman of the Animals or Plants Committee, is not satisfied that a range State has implemented the recommendations made by the Animals or Plants Committee in accordance with paragraph n) or o), it should recommend to the Standing Committee appropriate action, which may include, as a last resort, a suspension of trade in the affected species with [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ProcessReview_Details_21S {
            get {
                return ResourceManager.GetString("ProcessReview_Details_21S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage Details|&lt;b&gt;&lt;i&gt; Measures to be taken regarding the implementation of recommendations&lt;/b&gt;&lt;/i&gt;&lt;br&gt;&lt;br &gt;&lt;b&gt;s)&lt;/b&gt;when the Secretariat, having consulted with the Chairman of the Animals or Plants Committee, is not satisfied that a range State has implemented the recommendations made by the Animals or Plants Committee in accordance with paragraph n) or o), it should recommend to the Standing Committee appropriate action, which may include, as a last resort, a suspension of trade in the affected species with [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ProcessReview_Details_22S {
            get {
                return ResourceManager.GetString("ProcessReview_Details_22S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage Details|&lt;b&gt;&lt;i&gt; Measures to be taken regarding the implementation of recommendations&lt;/b&gt;&lt;/i&gt;&lt;br&gt;&lt;br &gt;&lt;b&gt;t)&lt;/b&gt; the Secretariat shall notify the Parties of any recommendations or actions taken by the Standing Committee.
        /// </summary>
        internal static string ProcessReview_Details_23T {
            get {
                return ResourceManager.GetString("ProcessReview_Details_23T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage Details|&lt;b&gt;&lt;i&gt; Measures to be taken regarding the implementation of recommendations&lt;/b&gt;&lt;/i&gt;&lt;br&gt;&lt;br &gt;&lt;b&gt;t)&lt;/b&gt; the Secretariat shall notify the Parties of any recommendations or actions taken by the Standing Committee.
        /// </summary>
        internal static string ProcessReview_Details_24T {
            get {
                return ResourceManager.GetString("ProcessReview_Details_24T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage Details|&lt;b&gt;&lt;i&gt; Measures to be taken regarding the implementation of recommendations&lt;/b&gt;&lt;/i&gt;&lt;br&gt;&lt;br &gt;&lt;b&gt;u)&lt;/b&gt; a recommendation to suspend trade in the affected species with the State concerned should be withdrawn only when that State demonstrates to the satisfaction of the Standing Committee, through the Secretariat, compliance with Article IV, paragraph 2 (a), 3 or 6 (a).
        /// </summary>
        internal static string ProcessReview_Details_25U {
            get {
                return ResourceManager.GetString("ProcessReview_Details_25U", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage Details|&lt;b&gt;&lt;i&gt; Measures to be taken regarding the implementation of recommendations&lt;/b&gt;&lt;/i&gt;&lt;br&gt;&lt;br &gt;&lt;b&gt;u)&lt;/b&gt; a recommendation to suspend trade in the affected species with the State concerned should be withdrawn only when that State demonstrates to the satisfaction of the Standing Committee, through the Secretariat, compliance with Article IV, paragraph 2 (a), 3 or 6 (a).
        /// </summary>
        internal static string ProcessReview_Details_26U {
            get {
                return ResourceManager.GetString("ProcessReview_Details_26U", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage Details|&lt;b&gt;&lt;i&gt; Measures to be taken regarding the implementation of recommendations&lt;/b&gt;&lt;/i&gt;&lt;br&gt;&lt;br &gt;&lt;b&gt;v)&lt;/b&gt; the Standing Committee, in consultation with the Secretariat and the Chairman of the Animals or Plants Committee, shall review recommendations to suspend trade that have been in place for longer than two years and, if appropriate, take measures to address the situation.
        /// </summary>
        internal static string ProcessReview_Details_27V {
            get {
                return ResourceManager.GetString("ProcessReview_Details_27V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage Details|&lt;b&gt;&lt;i&gt; Measures to be taken regarding the implementation of recommendations&lt;/b&gt;&lt;/i&gt;&lt;br&gt;&lt;br &gt;&lt;b&gt;v)&lt;/b&gt; the Standing Committee, in consultation with the Secretariat and the Chairman of the Animals or Plants Committee, shall review recommendations to suspend trade that have been in place for longer than two years and, if appropriate, take measures to address the situation.
        /// </summary>
        internal static string ProcessReview_Details_28V {
            get {
                return ResourceManager.GetString("ProcessReview_Details_28V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage Details|&lt;b&gt;&lt;i&gt; Measures to be taken regarding the implementation of recommendations&lt;/b&gt;&lt;/i&gt;&lt;br&gt;&lt;br &gt;&lt;b&gt;v)&lt;/b&gt; the Standing Committee, in consultation with the Secretariat and the Chairman of the Animals or Plants Committee, shall review recommendations to suspend trade that have been in place for longer than two years and, if appropriate, take measures to address the situation.
        /// </summary>
        internal static string ProcessReview_Details_29V {
            get {
                return ResourceManager.GetString("ProcessReview_Details_29V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status|Details of previous stages of the process can be viewed using &lt;i&gt;View History.&lt;/i&gt; The current stage is highlighed and is &lt;i&gt;In progress&lt;/i&gt;.  The current stage can be edited using Process.&lt;br&gt;&lt;br&gt; Once each stage is completed, details will be published on the website and the species/country combination will progress to the next stage (which is otherwise displayed as &lt;i&gt;Not yet applicable.&lt;/i&gt; .
        /// </summary>
        internal static string ProcessReview_Details_3 {
            get {
                return ResourceManager.GetString("ProcessReview_Details_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status|Details of previous stages can be viewed using &lt;i&gt;View History.&lt;/i&gt; The current stage can be edited using Process..
        /// </summary>
        internal static string ProcessReview_Details_4 {
            get {
                return ResourceManager.GetString("ProcessReview_Details_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage Details|&lt;b&gt;&lt;i&gt;Selection of species to be reviewed&lt;/b&gt;&lt;/i&gt;&lt;br&gt;&lt;br&gt;&lt;b&gt;a)&lt;/b&gt; the Secretariat shall request the UNEP World Conservation Monitoring Centre to produce, within 90 days after each meeting of the Conference of the Parties, a summary from the CITES database of annual report statistics showing the recorded net level of exports1 for Appendix-II species over the five most recent years; &lt;br&gt;&lt;br&gt;&lt;b&gt;b) &lt;/b&gt; on the basis of recorded trade levels and information available to the Animals or Plants Commi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ProcessReview_Details_5AtoC {
            get {
                return ResourceManager.GetString("ProcessReview_Details_5AtoC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage Details|&lt;b&gt;&lt;i&gt;Consultation with the range States concerning implementation of Article IV&lt;/b&gt;&lt;/i&gt;&lt;br&gt;&lt;br&gt;&lt;b&gt;d) &lt;/b&gt;the Secretariat shall, within 30 days after the meeting of the Animals or Plants Committee at which species are selected, notify range States of the species selected, providing an explanation for this selection and requesting comments regarding possible problems of implementing Article IV identified by the Committee. .
        /// </summary>
        internal static string ProcessReview_Details_6D {
            get {
                return ResourceManager.GetString("ProcessReview_Details_6D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage Details|&lt;b&gt;&lt;i&gt;Selection of species to be reviewed&lt;/b&gt;&lt;/i&gt;&lt;br&gt;&lt;br&gt;Range States shall be given 60 days to respond..
        /// </summary>
        internal static string ProcessReview_Details_7D {
            get {
                return ResourceManager.GetString("ProcessReview_Details_7D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage Details|&lt;b&gt;&lt;i&gt;Selection of species to be reviewed&lt;/b&gt;&lt;/i&gt;&lt;br&gt;&lt;br&gt;&lt;b&gt;e)&lt;/b&gt;the Secretariat shall report to the Animals or Plants Committee on the response of the range States concerned, including any other pertinent information.
        /// </summary>
        internal static string ProcessReview_Details_8E {
            get {
                return ResourceManager.GetString("ProcessReview_Details_8E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage Details|&lt;b&gt;&lt;i&gt;Selection of species to be reviewed&lt;/b&gt;&lt;/i&gt;&lt;br&gt;&lt;br&gt;&lt;b&gt;f)&lt;/b&gt;when the Animals or Plants Committee, having reviewed the available information, is satisfied that Article IV, paragraph 2 (a), 3 or 6 (a), is correctly implemented, the species shall be eliminated from the review with respect to the State concerned. In that event, the Secretariat shall notify the Parties accordingly within 60 days.
        /// </summary>
        internal static string ProcessReview_Details_9F {
            get {
                return ResourceManager.GetString("ProcessReview_Details_9F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hyperlink | If the location of a document on a website changes, this link will be broken.  &lt;br&gt;&lt;br&gt;It is preferable to upload documents if possible..
        /// </summary>
        internal static string ProcessReview_ParagraphDetails_Edit_Review_1 {
            get {
                return ResourceManager.GetString("ProcessReview_ParagraphDetails_Edit_Review_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decision Type|Select Decision type. New Decisions can be added by Administrators using the Site Admin &gt; Decisions &gt; Add Decisions.
        /// </summary>
        internal static string ProcessReview_ParagraphDetails_Edit_Review_11 {
            get {
                return ResourceManager.GetString("ProcessReview_ParagraphDetails_Edit_Review_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes| Add the reason for decision type. If a trade suspended,...
        /// </summary>
        internal static string ProcessReview_ParagraphDetails_Edit_Review_12 {
            get {
                return ResourceManager.GetString("ProcessReview_ParagraphDetails_Edit_Review_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suspension Lifted Date|Add the data the suspension was lifted.
        /// </summary>
        internal static string ProcessReview_ParagraphDetails_Edit_Review_13 {
            get {
                return ResourceManager.GetString("ProcessReview_ParagraphDetails_Edit_Review_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade Terms| Select the term for which trade is suspended. Additional trade terms can be added by.....
        /// </summary>
        internal static string ProcessReview_ParagraphDetails_Edit_Review_14 {
            get {
                return ResourceManager.GetString("ProcessReview_ParagraphDetails_Edit_Review_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decision/Suspension Date|.
        /// </summary>
        internal static string ProcessReview_ParagraphDetails_Edit_Review_15 {
            get {
                return ResourceManager.GetString("ProcessReview_ParagraphDetails_Edit_Review_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting at which suspension was established|Add relevent meeting .
        /// </summary>
        internal static string ProcessReview_ParagraphDetails_Edit_Review_16 {
            get {
                return ResourceManager.GetString("ProcessReview_ParagraphDetails_Edit_Review_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting at which suspension was lifted|Add relevent meeting.
        /// </summary>
        internal static string ProcessReview_ParagraphDetails_Edit_Review_17 {
            get {
                return ResourceManager.GetString("ProcessReview_ParagraphDetails_Edit_Review_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents| A document may include Standing Committee documents which explain the reasons why a trade suspension has been implemented or withdrawn, or correspondence from range States. &lt;br&gt;&lt;br&gt;The Secretariat will be notified when new documents are added..
        /// </summary>
        internal static string ProcessReview_ParagraphDetails_Edit_Review_18 {
            get {
                return ResourceManager.GetString("ProcessReview_ParagraphDetails_Edit_Review_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed|Tick the checkbox if the stage of the process (a-v) has been completed. The status will then progress to the next stage in the process..
        /// </summary>
        internal static string ProcessReview_ParagraphDetails_Edit_Review_19 {
            get {
                return ResourceManager.GetString("ProcessReview_ParagraphDetails_Edit_Review_19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments|Add a comment to describe documents uploaded or linked by a hyperlink .
        /// </summary>
        internal static string ProcessReview_ParagraphDetails_Edit_Review_2 {
            get {
                return ResourceManager.GetString("ProcessReview_ParagraphDetails_Edit_Review_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents|A document may include correspondence between the range State and the Secretariat.  &lt;br&gt;&lt;br&gt;The Secretariat will be notified when new documents are added..
        /// </summary>
        internal static string ProcessReview_ParagraphDetails_Edit_Review_3 {
            get {
                return ResourceManager.GetString("ProcessReview_ParagraphDetails_Edit_Review_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document name | Name files using the following protocol: Genus_species_two letter ISOcountry code.doc. For example:  Prunus_africana_KE.  Use underscores rather than spaces,  and avoid using characters that are not letters of the alphabet..
        /// </summary>
        internal static string ProcessReview_ParagraphDetails_Edit_Review_4 {
            get {
                return ResourceManager.GetString("ProcessReview_ParagraphDetails_Edit_Review_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Rights| Document viewing is  limited by access rights. .
        /// </summary>
        internal static string ProcessReview_ParagraphDetails_Edit_Review_5 {
            get {
                return ResourceManager.GetString("ProcessReview_ParagraphDetails_Edit_Review_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommendation|Each recommendation directed to the range State should be added individually in full, e.g. &lt;i&gt;&quot;Develop a scientifically-based survey to establish the population status of the species in the country&quot;. &lt;/i&gt;Each recommendation will have a specific timeframe for implememtation..
        /// </summary>
        internal static string ProcessReview_ParagraphDetails_Edit_Review_6 {
            get {
                return ResourceManager.GetString("ProcessReview_ParagraphDetails_Edit_Review_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommendation Date|Add the date the recommendation was formulated at the relevant Committee meeting.
        /// </summary>
        internal static string ProcessReview_ParagraphDetails_Edit_Review_7 {
            get {
                return ResourceManager.GetString("ProcessReview_ParagraphDetails_Edit_Review_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Committee |Select the meeting at which the recommendation was formulated. New meetings can be added by Administrators using the Side Admin &gt; Meetings &gt; New Meeting.
        /// </summary>
        internal static string ProcessReview_ParagraphDetails_Edit_Review_8 {
            get {
                return ResourceManager.GetString("ProcessReview_ParagraphDetails_Edit_Review_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deadline Date|Add the deadline for implementation of the recommendation as determined by the Animals of Plants Committee.
        /// </summary>
        internal static string ProcessReview_ParagraphDetails_Edit_Review_9 {
            get {
                return ResourceManager.GetString("ProcessReview_ParagraphDetails_Edit_Review_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator |.
        /// </summary>
        internal static string Role_Index_1 {
            get {
                return ResourceManager.GetString("Role_Index_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Contributor |.
        /// </summary>
        internal static string Role_Index_2 {
            get {
                return ResourceManager.GetString("Role_Index_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Manager |.
        /// </summary>
        internal static string Role_Index_3 {
            get {
                return ResourceManager.GetString("Role_Index_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Viewer |.
        /// </summary>
        internal static string Role_Index_4 {
            get {
                return ResourceManager.GetString("Role_Index_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intermediate Viewer |.
        /// </summary>
        internal static string Role_Index_5 {
            get {
                return ResourceManager.GetString("Role_Index_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public Viewer |.
        /// </summary>
        internal static string Role_Index_6 {
            get {
                return ResourceManager.GetString("Role_Index_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by Country|Only countries that are currently subject to the Significant Trade Review process or have been previously eliminated from the review are included..
        /// </summary>
        internal static string SearchByCountry {
            get {
                return ResourceManager.GetString("SearchByCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by Species | Type in at least the first three letters of the species required. Species containing this search string in any part of the taxon name will appear in the drop-down box below. &lt;br&gt;&lt;br&gt; Animals are denoted by (An) and Plants by (Pl)&lt;br&gt;&lt;br&gt;The search results will only display species that have been included in the Review of Significant Trade. &lt;br&gt;&lt;br&gt;
        ///The search tool is not case sensitive..
        /// </summary>
        internal static string SearchFreeSearch {
            get {
                return ResourceManager.GetString("SearchFreeSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Genus|Only genera that are currently subject to the Significant Trade Review or have been previously eliminated from the review are included..
        /// </summary>
        internal static string SelectGenus {
            get {
                return ResourceManager.GetString("SelectGenus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Phase|The selection process for adding new species for the Significant Trade Review takes place periodically in Phases.&lt;br&gt;  A new Phase now follows every meeting of the Conference of the Parties..
        /// </summary>
        internal static string SelectPhase {
            get {
                return ResourceManager.GetString("SelectPhase", resourceCulture);
            }
        }
    }
}
